import {
  LayoutDashboard,
  List,
  DoorOpen,
  Bed,
  Receipt,
  FileText,
  FileBarChart,
  Settings,
} from 'lucide-react';

export const hotelAdminNavItems = [
  {
    id: 'HA_DASHBOARD',
    name: 'Dashboard',
    label: 'Dashboard',
    navigate: '/hotel-admin/dashboard',
    path: '/hotel-admin/dashboard',
    icon: LayoutDashboard,
  },
  {
    id: 'HA_BOOKINGS',
    name: 'Bookings List',
    label: 'Bookings List',
    navigate: '/hotel-admin/bookings',
    path: '/hotel-admin/bookings',
    icon: List,
  },
  {
    id: 'HA_ROOMS',
    name: 'Room Management',
    label: 'Room Management',
    navigate: '/hotel-admin/rooms',
    path: '/hotel-admin/rooms',
    icon: DoorOpen,
  },
  {
    id: 'HA_BEDS',
    name: 'Bed Management',
    label: 'Bed Management',
    navigate: '/hotel-admin/beds',
    path: '/hotel-admin/beds',
    icon: Bed,
  },
  {
    id: 'HA_INVOICES',
    name: 'Invoice List',
    label: 'Invoice List',
    navigate: '/hotel-admin/invoices',
    path: '/hotel-admin/invoices',
    icon: Receipt,
  },
  {
    id: 'HA_RECEIPTS',
    name: 'Outstanding Receipts',
    label: 'Outstanding Receipts',
    navigate: '/hotel-admin/receipts',
    path: '/hotel-admin/receipts',
    icon: FileText,
  },
  {
    id: 'HA_REPORTS',
    name: 'Reports',
    label: 'Reports',
    navigate: '/hotel-admin/reports',
    path: '/hotel-admin/reports',
    icon: FileBarChart,
  },
  {
    id: 'HA_CONFIGURATION',
    name: 'Configuration',
    label: 'Configuration',
    navigate: '/hotel-admin/configuration',
    path: '/hotel-admin/configuration',
    icon: Settings,
  },
];
